monolog:
  channels: ['app']
  handlers:
    main:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
      channels: ["!event"]
      formatter: monolog.formatter.json
    console:
      type: console
      process_psr_3_messages: true
      channels: ["!event", "!doctrine", "!console"]
      formatter: monolog.formatter.json

services:
  monolog.formatter.json:
    class: Monolog\Formatter\JsonFormatter
